### ISSUE TITLE
Class Not found exception

### ISSUE THREAD

**Issue by stripathi669** [HeinrichReimer/Android-SingleInputForm#5]
Hi,

I am facing Class not found exception:
================= From Logs ====================
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.heinrichreimersoftware.singleinputform.R$layout" on path: DexPathList[[zip file "/data/app/my.package,name/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]] 

===========
I am using exact same code as in the examples, except the fact that this form is being launched from another activity.

I can also post stack trace in-case required.

I would be grateful for any help.

UPDATE: Trace stack:

======================================================
01-03 16:37:45.461    8963-8963/my.package.name E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: recommned.contect.web.iwrs, PID: 8963
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/heinrichreimersoftware/singleinputform/R$layout;
            at com.heinrichreimersoftware.singleinputform.SingleInputFormActivity.onCreate(SingleInputFormActivity.java:112)
            at android.app.Activity.performCreate(Activity.java:5933)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.heinrichreimersoftware.singleinputform.R$layout" on path: DexPathList[[zip file "/data/app/my.package.name-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at com.heinrichreimersoftware.singleinputform.SingleInputFormActivity.onCreate(SingleInputFormActivity.java:112)
            at android.app.Activity.performCreate(Activity.java:5933)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
    Suppressed: java.lang.ClassNotFoundException: com.heinrichreimersoftware.singleinputform.R$layout
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 15 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by HeinrichReimer** [comment]
Ok would than be great if you post your stack trace. I guess you have overwritten a layout file from the library.

**Comment by stripathi669** [comment]
Thankyou for your consideration. I have updated original post with full trace stack.
Also, I ran the example provided in the repository. It throws the same exception:

=====================================================
01-03 16:12:04.018    6748-6748/com.heinrichreimersoftware.singleinputform.example E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.heinrichreimersoftware.singleinputform.example, PID: 6748
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/heinrichreimersoftware/singleinputform/R$layout;
            at com.heinrichreimersoftware.singleinputform.SingleInputFormActivity.onCreate(SingleInputFormActivity.java:112)
            at android.app.Activity.performCreate(Activity.java:5933)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.heinrichreimersoftware.singleinputform.R$layout" on path: DexPathList[[zip file "/data/app/com.heinrichreimersoftware.singleinputform.example-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at com.heinrichreimersoftware.singleinputform.SingleInputFormActivity.onCreate(SingleInputFormActivity.java:112)
            at android.app.Activity.performCreate(Activity.java:5933)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
    Suppressed: java.lang.ClassNotFoundException: com.heinrichreimersoftware.singleinputform.R$layout
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 15 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available.

======================================================================

**Comment by HeinrichReimer** [comment]
That's strange. There is no point where I can see a reason for this error. Can you post your code here? May be some issue with proguard...

**Comment by stripathi669** [comment]
As stated in my second post, I am running the example from the repository with absolutely no modifications (on Lollipop device). I am posting build.gradle file for reference.

======

apply plugin: 'android'

android {
	compileSdkVersion 21
	buildToolsVersion "19.1.0"

	defaultConfig {
		applicationId "com.heinrichreimersoftware.singleinputform.example"
		minSdkVersion 9
		targetSdkVersion 19
		versionCode 1
		versionName "1.0"
	}
	buildTypes {
		release {
			runProguard false
			proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
		}
	}
}

dependencies {
   compile project(':library')
    compile 'com.android.support:appcompat-v7:19.+'

}

//apply from: 'https://raw.github.com/chrisbanes/gradle-mvn-push/master/gradle-mvn-push.gradle'

===

**Comment by HeinrichReimer** [comment]
This line:

    compile project(':library')

should be replaced by this line:

    compile 'com.heinrichreimersoftware.singleinputform:library:1.0'

**Comment by stripathi669** [comment]
I am sorry I should have mentioned before, but the library is the library from this repo. Also, I tried the suggestion you posted, and it gives the same error. Do you think version of android could be the issue ?

**Comment by HeinrichReimer** [comment]
No, the SDK version shouldn't be the issue here. Strange thing...

May something like this be the issue?
http://stackoverflow.com/a/15894284/2037482

**Comment by stripathi669** [comment]
The link you posted specifically talks about the problems where resource don't exists or the library has not been imported properly in Eclipse.

My issue is more like this one: 
1. http://stackoverflow.com/questions/25194024/java-lang-noclassdeffounderror-com-acme-rlayout-referencing-android-library
2. https://code.google.com/p/android/issues/detail?id=75456

What do you think ?

**Comment by stripathi669** [comment]
Hey thanks. I solved the problem by upgrading to latest version of gradle. Seems like 0.13 version was causing the problem.

It works if I use it by importing library. (Maven repo still gives the same error)

You may close the issue if you wish to.
